### ISSUE TITLE
Is it possible to create new VPS via api?

### ISSUE THREAD

**Issue by alemar11** [ovh/node-ovh#23]
Is this feature implemented/supported?
Thanks

**Comment by PedroMD** [comment]
I would also like to have the recipe, please. The API is very confusing and I'm guessing one can't really automate this whole process without human intervention, right? It looks like the billing process must be finalized through the web platform... 

Any help or feedback would be much appreciated. 

Thanks in advance

**Comment by rbeuque74** [comment]
Hello,
You should have a look to this repository https://github.com/ovh/order-cart-examples, explaining how to order products using OVH API.

By the way, this issue is not linked to node-ovh, please use the community mailing-list as described here: https://github.com/ovh/node-ovh#ovh-europe

Pending close.
